[project]
name = "vmc-lamart-backend"
version = "0.1.0"
description = ""
authors = [
    {name = "EB",email = "122553720+EgorkaaBadddy@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi (==0.103.2)",
    "uvicorn (==0.22.0)",
    "pydantic (>=2.12.5,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[virtualenvs]
in-project = true


